 #DEV environment 

app:
    message: This is property   file fo the ${spring.application.name} specific to DEV Environment
 
spring:
    datasource: 
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: <MYSQL_URL>
        username: <USERNAME>
        password: <PASSWORD>